name: Android Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Zip Package
        run: |
          mkdir -p output
          zip -r output/my-app.zip .

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyWebsiteApp
          path: output/my-app.zip
